//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassicAssist.Updater.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClassicAssist.Updater.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured....
        /// </summary>
        public static string An_error_occured___ {
            get {
                return ResourceManager.GetString("An error occured...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot locate update package....
        /// </summary>
        public static string Cannot_locate_update_package___ {
            get {
                return ResourceManager.GetString("Cannot locate update package...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking for latest release....
        /// </summary>
        public static string Checking_for_latest_release___ {
            get {
                return ResourceManager.GetString("Checking for latest release...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClassicAssist Updater.
        /// </summary>
        public static string ClassicAssist_Updater {
            get {
                return ResourceManager.GetString("ClassicAssist Updater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copying {0}....
        /// </summary>
        public static string Copying__0____ {
            get {
                return ResourceManager.GetString("Copying {0}...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done..
        /// </summary>
        public static string Done_ {
            get {
                return ResourceManager.GetString("Done.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloaded.
        /// </summary>
        public static string Downloaded {
            get {
                return ResourceManager.GetString("Downloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloaded size doesn&apos;t match expected....
        /// </summary>
        public static string Downloaded_size_doesn_t_match_expected___ {
            get {
                return ResourceManager.GetString("Downloaded size doesn\'t match expected...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading.
        /// </summary>
        public static string Downloading {
            get {
                return ResourceManager.GetString("Downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error:.
        /// </summary>
        public static string Error_ {
            get {
                return ResourceManager.GetString("Error:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extracting package....
        /// </summary>
        public static string Extracting_package___ {
            get {
                return ResourceManager.GetString("Extracting package...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GitHub rate limit, try again after {0}.
        /// </summary>
        public static string GitHub_rate_limit__try_again_after__0_ {
            get {
                return ResourceManager.GetString("GitHub rate limit, try again after {0}", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest Release:.
        /// </summary>
        public static string Latest_Release_ {
            get {
                return ResourceManager.GetString("Latest Release:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No new release available....
        /// </summary>
        public static string No_new_release_available___ {
            get {
                return ResourceManager.GetString("No new release available...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No release asset....
        /// </summary>
        public static string No_release_asset___ {
            get {
                return ResourceManager.GetString("No release asset...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Homepage.
        /// </summary>
        public static string Project_Homepage {
            get {
                return ResourceManager.GetString("Project Homepage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relaunching updater....
        /// </summary>
        public static string Relaunching_updater___ {
            get {
                return ResourceManager.GetString("Relaunching updater...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Releases.
        /// </summary>
        public static string Releases {
            get {
                return ResourceManager.GetString("Releases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to locate GitHub release.
        /// </summary>
        public static string Unable_to_locate_GitHub_release {
            get {
                return ResourceManager.GetString("Unable to locate GitHub release", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating files....
        /// </summary>
        public static string Updating_files___ {
            get {
                return ResourceManager.GetString("Updating files...", resourceCulture);
            }
        }
    }
}
