//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassicAssist.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClassicAssist.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abilities.
        /// </summary>
        public static string Abilities {
            get {
                return ResourceManager.GetString("Abilities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action Delay:.
        /// </summary>
        public static string Action_Delay_ {
            get {
                return ResourceManager.GetString("Action Delay:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Objects.
        /// </summary>
        public static string Active_Objects {
            get {
                return ResourceManager.GetString("Active Objects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address:.
        /// </summary>
        public static string Address_ {
            get {
                return ResourceManager.GetString("Address:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agents.
        /// </summary>
        public static string Agents {
            get {
                return ResourceManager.GetString("Agents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aliases.
        /// </summary>
        public static string Aliases {
            get {
                return ResourceManager.GetString("Aliases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always On Top.
        /// </summary>
        public static string Always_On_Top {
            get {
                return ResourceManager.GetString("Always On Top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bandage Self.
        /// </summary>
        public static string Bandage_Self {
            get {
                return ResourceManager.GetString("Bandage Self", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bought.
        /// </summary>
        public static string Bought {
            get {
                return ResourceManager.GetString("Bought", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buffs / Penalties.
        /// </summary>
        public static string Buffs___Penalties {
            get {
                return ResourceManager.GetString("Buffs / Penalties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build Date:.
        /// </summary>
        public static string Build_Date_ {
            get {
                return ResourceManager.GetString("Build Date:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find container....
        /// </summary>
        public static string Cannot_find_container___ {
            get {
                return ResourceManager.GetString("Cannot find container...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find item....
        /// </summary>
        public static string Cannot_find_item___ {
            get {
                return ResourceManager.GetString("Cannot find item...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture Packets.
        /// </summary>
        public static string Capture_Packets {
            get {
                return ResourceManager.GetString("Capture Packets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character.
        /// </summary>
        public static string Character {
            get {
                return ResourceManager.GetString("Character", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear All.
        /// </summary>
        public static string Clear_All {
            get {
                return ResourceManager.GetString("Clear All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear All Objects.
        /// </summary>
        public static string Clear_All_Objects {
            get {
                return ResourceManager.GetString("Clear All Objects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        public static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combat.
        /// </summary>
        public static string Combat {
            get {
                return ResourceManager.GetString("Combat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commands.
        /// </summary>
        public static string Commands {
            get {
                return ResourceManager.GetString("Commands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected:.
        /// </summary>
        public static string Connected_ {
            get {
                return ResourceManager.GetString("Connected:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count.
        /// </summary>
        public static string Count {
            get {
                return ResourceManager.GetString("Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Counter &quot;{0}&quot; amount is now {1}....
        /// </summary>
        public static string Counter___0___amount_is_now__1____ {
            get {
                return ResourceManager.GetString("Counter \"{0}\" amount is now {1}...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Counters.
        /// </summary>
        public static string Counters {
            get {
                return ResourceManager.GetString("Counters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not auto interupt.
        /// </summary>
        public static string Do_not_auto_interupt {
            get {
                return ResourceManager.GetString("Do not auto interupt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dress.
        /// </summary>
        public static string Dress {
            get {
                return ResourceManager.GetString("Dress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        public static string Enabled {
            get {
                return ResourceManager.GetString("Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity.
        /// </summary>
        public static string Entity {
            get {
                return ResourceManager.GetString("Entity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity Collection Viewer.
        /// </summary>
        public static string Entity_Collection_Viewer {
            get {
                return ResourceManager.GetString("Entity Collection Viewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity not found....
        /// </summary>
        public static string Entity_not_found___ {
            get {
                return ResourceManager.GetString("Entity not found...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity Viewer.
        /// </summary>
        public static string Entity_Viewer {
            get {
                return ResourceManager.GetString("Entity Viewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Cannot find player backpack.
        /// </summary>
        public static string Error__Cannot_find_player_backpack {
            get {
                return ResourceManager.GetString("Error: Cannot find player backpack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Cannot find type.
        /// </summary>
        public static string Error__Cannot_find_type {
            get {
                return ResourceManager.GetString("Error: Cannot find type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: No Player.
        /// </summary>
        public static string Error__No_Player {
            get {
                return ResourceManager.GetString("Error: No Player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute.
        /// </summary>
        public static string Execute {
            get {
                return ResourceManager.GetString("Execute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filters.
        /// </summary>
        public static string Filters {
            get {
                return ResourceManager.GetString("Filters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graphic.
        /// </summary>
        public static string Graphic {
            get {
                return ResourceManager.GetString("Graphic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gumps.
        /// </summary>
        public static string Gumps {
            get {
                return ResourceManager.GetString("Gumps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotkeys.
        /// </summary>
        public static string Hotkeys {
            get {
                return ResourceManager.GetString("Hotkeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore ping packets.
        /// </summary>
        public static string Ignore_ping_packets {
            get {
                return ResourceManager.GetString("Ignore ping packets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        public static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include Backpack Amount.
        /// </summary>
        public static string Include_Backpack_Amount {
            get {
                return ResourceManager.GetString("Include Backpack Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include Purchased Amount.
        /// </summary>
        public static string Include_Purchased_Amount {
            get {
                return ResourceManager.GetString("Include Purchased Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert.
        /// </summary>
        public static string Insert {
            get {
                return ResourceManager.GetString("Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid container....
        /// </summary>
        public static string Invalid_container___ {
            get {
                return ResourceManager.GetString("Invalid container...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid counter agent name....
        /// </summary>
        public static string Invalid_counter_agent_name___ {
            get {
                return ResourceManager.GetString("Invalid counter agent name...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid destination container....
        /// </summary>
        public static string Invalid_destination_container___ {
            get {
                return ResourceManager.GetString("Invalid destination container...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid layer value....
        /// </summary>
        public static string Invalid_layer_value___ {
            get {
                return ResourceManager.GetString("Invalid layer value...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid mount....
        /// </summary>
        public static string Invalid_mount___ {
            get {
                return ResourceManager.GetString("Invalid mount...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid or unknown object id.
        /// </summary>
        public static string Invalid_or_unknown_object_id {
            get {
                return ResourceManager.GetString("Invalid or unknown object id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid skill name &quot;{0}&quot;.
        /// </summary>
        public static string Invalid_skill_name___0__ {
            get {
                return ResourceManager.GetString("Invalid skill name \"{0}\"", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid source container....
        /// </summary>
        public static string Invalid_source_container___ {
            get {
                return ResourceManager.GetString("Invalid source container...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item.
        /// </summary>
        public static string Item {
            get {
                return ResourceManager.GetString("Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items:.
        /// </summary>
        public static string Items_ {
            get {
                return ResourceManager.GetString("Items:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journal.
        /// </summary>
        public static string Journal {
            get {
                return ResourceManager.GetString("Journal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Target.
        /// </summary>
        public static string Last_Target {
            get {
                return ResourceManager.GetString("Last Target", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Target:.
        /// </summary>
        public static string Last_Target_ {
            get {
                return ResourceManager.GetString("Last Target:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latency:.
        /// </summary>
        public static string Latency_ {
            get {
                return ResourceManager.GetString("Latency:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string Light {
            get {
                return ResourceManager.GetString("Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light Level.
        /// </summary>
        public static string Light_Level {
            get {
                return ResourceManager.GetString("Light Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lists.
        /// </summary>
        public static string Lists {
            get {
                return ResourceManager.GetString("Lists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location:.
        /// </summary>
        public static string Location_ {
            get {
                return ResourceManager.GetString("Location:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loop.
        /// </summary>
        public static string Loop {
            get {
                return ResourceManager.GetString("Loop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Macros.
        /// </summary>
        public static string Macros {
            get {
                return ResourceManager.GetString("Macros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magical.
        /// </summary>
        public static string Magical {
            get {
                return ResourceManager.GetString("Magical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main.
        /// </summary>
        public static string Main {
            get {
                return ResourceManager.GetString("Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map:.
        /// </summary>
        public static string Map_ {
            get {
                return ResourceManager.GetString("Map:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Price.
        /// </summary>
        public static string Max_Price {
            get {
                return ResourceManager.GetString("Max Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Misc.
        /// </summary>
        public static string Misc {
            get {
                return ResourceManager.GetString("Misc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile.
        /// </summary>
        public static string Mobile {
            get {
                return ResourceManager.GetString("Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile not found....
        /// </summary>
        public static string Mobile_not_found___ {
            get {
                return ResourceManager.GetString("Mobile not found...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobiles:.
        /// </summary>
        public static string Mobiles_ {
            get {
                return ResourceManager.GetString("Mobiles:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move conflicting items.
        /// </summary>
        public static string Move_conflicting_items {
            get {
                return ResourceManager.GetString("Move conflicting items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        public static string Name_ {
            get {
                return ResourceManager.GetString("Name:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Item.
        /// </summary>
        public static string New_Item {
            get {
                return ResourceManager.GetString("New Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object Inspector.
        /// </summary>
        public static string Object_Inspector {
            get {
                return ResourceManager.GetString("Object Inspector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objects.
        /// </summary>
        public static string Objects {
            get {
                return ResourceManager.GetString("Objects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organizer.
        /// </summary>
        public static string Organizer {
            get {
                return ResourceManager.GetString("Organizer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organizer &quot;{0}&quot; not found....
        /// </summary>
        public static string Organizer___0___not_found___ {
            get {
                return ResourceManager.GetString("Organizer \"{0}\" not found...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organizer &quot;{0}&quot; finished....
        /// </summary>
        public static string Organizer__0__finished___ {
            get {
                return ResourceManager.GetString("Organizer {0} finished...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organizer &quot;{0}&quot; running....
        /// </summary>
        public static string Organizer__0__running___ {
            get {
                return ResourceManager.GetString("Organizer {0} running...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organizer containers set....
        /// </summary>
        public static string Organizer_containers_set___ {
            get {
                return ResourceManager.GetString("Organizer containers set...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pass to UO.
        /// </summary>
        public static string Pass_to_UO {
            get {
                return ResourceManager.GetString("Pass to UO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        public static string Play {
            get {
                return ResourceManager.GetString("Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player.
        /// </summary>
        public static string Player {
            get {
                return ResourceManager.GetString("Player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port:.
        /// </summary>
        public static string Port_ {
            get {
                return ResourceManager.GetString("Port:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product:.
        /// </summary>
        public static string Product_ {
            get {
                return ResourceManager.GetString("Product:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClassicAssist.
        /// </summary>
        public static string ProductName {
            get {
                return ResourceManager.GetString("ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profiles.
        /// </summary>
        public static string Profiles {
            get {
                return ResourceManager.GetString("Profiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property.
        /// </summary>
        public static string Property {
            get {
                return ResourceManager.GetString("Property", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public Properties.
        /// </summary>
        public static string Public_Properties {
            get {
                return ResourceManager.GetString("Public Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready....
        /// </summary>
        public static string Ready___ {
            get {
                return ResourceManager.GetString("Ready...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record.
        /// </summary>
        public static string Record {
            get {
                return ResourceManager.GetString("Record", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recount.
        /// </summary>
        public static string Recount {
            get {
                return ResourceManager.GetString("Recount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regeneration.
        /// </summary>
        public static string Regeneration {
            get {
                return ResourceManager.GetString("Regeneration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resistances.
        /// </summary>
        public static string Resistances {
            get {
                return ResourceManager.GetString("Resistances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resync.
        /// </summary>
        public static string Resync {
            get {
                return ResourceManager.GetString("Resync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seasons.
        /// </summary>
        public static string Seasons {
            get {
                return ResourceManager.GetString("Seasons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select destination container....
        /// </summary>
        public static string Select_destination_container___ {
            get {
                return ResourceManager.GetString("Select destination container...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select source container....
        /// </summary>
        public static string Select_source_container___ {
            get {
                return ResourceManager.GetString("Select source container...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select undress container....
        /// </summary>
        public static string Select_undress_container___ {
            get {
                return ResourceManager.GetString("Select undress container...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial.
        /// </summary>
        public static string Serial {
            get {
                return ResourceManager.GetString("Serial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial:.
        /// </summary>
        public static string Serial_ {
            get {
                return ResourceManager.GetString("Serial:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server.
        /// </summary>
        public static string Server {
            get {
                return ResourceManager.GetString("Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Containers.
        /// </summary>
        public static string Set_Containers {
            get {
                return ResourceManager.GetString("Set Containers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Undress Container.
        /// </summary>
        public static string Set_Undress_Container {
            get {
                return ResourceManager.GetString("Set Undress Container", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show World Items.
        /// </summary>
        public static string Show_World_Items {
            get {
                return ResourceManager.GetString("Show World Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skills.
        /// </summary>
        public static string Skills {
            get {
                return ResourceManager.GetString("Skills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software.
        /// </summary>
        public static string Software {
            get {
                return ResourceManager.GetString("Software", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stack.
        /// </summary>
        public static string Stack {
            get {
                return ResourceManager.GetString("Stack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stats.
        /// </summary>
        public static string Stats {
            get {
                return ResourceManager.GetString("Stats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status:.
        /// </summary>
        public static string Status_ {
            get {
                return ResourceManager.GetString("Status:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target clothing item....
        /// </summary>
        public static string Target_clothing_item___ {
            get {
                return ResourceManager.GetString("Target clothing item...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target new item....
        /// </summary>
        public static string Target_new_item___ {
            get {
                return ResourceManager.GetString("Target new item...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target new mount....
        /// </summary>
        public static string Target_new_mount___ {
            get {
                return ResourceManager.GetString("Target new mount...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target object....
        /// </summary>
        public static string Target_object___ {
            get {
                return ResourceManager.GetString("Target object...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target timeout....
        /// </summary>
        public static string Target_timeout___ {
            get {
                return ResourceManager.GetString("Target timeout...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The item needs to be equipped....
        /// </summary>
        public static string The_item_needs_to_be_equipped___ {
            get {
                return ResourceManager.GetString("The item needs to be equipped...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout....
        /// </summary>
        public static string Timeout___ {
            get {
                return ResourceManager.GetString("Timeout...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timers.
        /// </summary>
        public static string Timers {
            get {
                return ResourceManager.GetString("Timers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topmost.
        /// </summary>
        public static string Topmost {
            get {
                return ResourceManager.GetString("Topmost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undress.
        /// </summary>
        public static string Undress {
            get {
                return ResourceManager.GetString("Undress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown alias &quot;{0}&quot;..
        /// </summary>
        public static string Unknown_alias___0___ {
            get {
                return ResourceManager.GetString("Unknown alias \"{0}\".", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown dress agent &quot;{0}&quot;..
        /// </summary>
        public static string Unknown_dress_agent___0___ {
            get {
                return ResourceManager.GetString("Unknown dress agent \"{0}\".", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ENU.
        /// </summary>
        public static string UO_LOCALE {
            get {
                return ResourceManager.GetString("UO_LOCALE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use death screen whilst hidden (Chuckles Mode).
        /// </summary>
        public static string Use_death_screen_whilst_hidden {
            get {
                return ResourceManager.GetString("Use death screen whilst hidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UseOnce: Cannot find type....
        /// </summary>
        public static string UseOnce__Cannot_find_type___ {
            get {
                return ResourceManager.GetString("UseOnce: Cannot find type...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UseOnce cleared....
        /// </summary>
        public static string UseOnce_cleared___ {
            get {
                return ResourceManager.GetString("UseOnce cleared...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor Buy.
        /// </summary>
        public static string Vendor_Buy {
            get {
                return ResourceManager.GetString("Vendor Buy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version:.
        /// </summary>
        public static string Version_ {
            get {
                return ResourceManager.GetString("Version:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warn when counter amount below:.
        /// </summary>
        public static string Warn_when_counter_amount_below_ {
            get {
                return ResourceManager.GetString("Warn when counter amount below:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weather.
        /// </summary>
        public static string Weather {
            get {
                return ResourceManager.GetString("Weather", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to World Status.
        /// </summary>
        public static string World_Status {
            get {
                return ResourceManager.GetString("World_Status", resourceCulture);
            }
        }
    }
}
