//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassicAssist.Launcher.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClassicAssist.Launcher.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Plugins.
        /// </summary>
        public static string Additional_Plugins_ {
            get {
                return ResourceManager.GetString("Additional Plugins:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Reconnect.
        /// </summary>
        public static string Auto_Reconnect {
            get {
                return ResourceManager.GetString("Auto Reconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autologin.
        /// </summary>
        public static string Autologin {
            get {
                return ResourceManager.GetString("Autologin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot remove preset shard.
        /// </summary>
        public static string Cannot_remove_preset_shard {
            get {
                return ResourceManager.GetString("Cannot remove preset shard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for update.
        /// </summary>
        public static string Check_for_update {
            get {
                return ResourceManager.GetString("Check for update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClassicAssist Launcher.
        /// </summary>
        public static string ClassicAssist_Launcher {
            get {
                return ResourceManager.GetString("ClassicAssist Launcher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Options.
        /// </summary>
        public static string Client_Options {
            get {
                return ResourceManager.GetString("Client Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Version.
        /// </summary>
        public static string Client_Version {
            get {
                return ResourceManager.GetString("Client Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug.
        /// </summary>
        public static string Debug {
            get {
                return ResourceManager.GetString("Debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encryption.
        /// </summary>
        public static string Encryption {
            get {
                return ResourceManager.GetString("Encryption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open a GitHub issue to have your shard added to the list..
        /// </summary>
        public static string Open_a_GitHub_issue_to_have_your_shard_added_to_the_list_ {
            get {
                return ResourceManager.GetString("Open a GitHub issue to have your shard added to the list.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Shard Website.
        /// </summary>
        public static string Open_Shard_Website {
            get {
                return ResourceManager.GetString("Open Shard Website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Override Client Version.
        /// </summary>
        public static string Override_Client_Version {
            get {
                return ResourceManager.GetString("Override Client Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ping.
        /// </summary>
        public static string Ping {
            get {
                return ResourceManager.GetString("Ping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Players.
        /// </summary>
        public static string Players {
            get {
                return ResourceManager.GetString("Players", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        public static string Port {
            get {
                return ResourceManager.GetString("Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reconnect Time:.
        /// </summary>
        public static string Reconnect_Time {
            get {
                return ResourceManager.GetString("Reconnect Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reconnect Time (milliseconds).
        /// </summary>
        public static string Reconnect_Time__milliseconds_ {
            get {
                return ResourceManager.GetString("Reconnect Time (milliseconds)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a client.
        /// </summary>
        public static string Select_a_client {
            get {
                return ResourceManager.GetString("Select a client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select your Ultima Online directory.
        /// </summary>
        public static string Select_your_Ultima_Online_directory {
            get {
                return ResourceManager.GetString("Select your Ultima Online directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shard.
        /// </summary>
        public static string Shard {
            get {
                return ResourceManager.GetString("Shard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shards.
        /// </summary>
        public static string Shards {
            get {
                return ResourceManager.GetString("Shards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip Login Screen.
        /// </summary>
        public static string Skip_Login_Screen {
            get {
                return ResourceManager.GetString("Skip Login Screen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ultima Online.
        /// </summary>
        public static string Ultima_Online {
            get {
                return ResourceManager.GetString("Ultima Online", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to resolve shard hostname..
        /// </summary>
        public static string Unable_to_resolve_shard_hostname_ {
            get {
                return ResourceManager.GetString("Unable to resolve shard hostname.", resourceCulture);
            }
        }
    }
}
