using System;
using System.Collections;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Text;
using System.Threading;

// ReSharper disable LocalizableElement

namespace ExportCommands
{
    /// <summary>
    ///     Generates Python type stub (.pyi) files for macro commands so that external editors
    ///     (VS Code / Pylance) can provide autocomplete and signature help for file-based macros.
    ///     Reflects over the loaded ClassicAssist assembly rather than referencing the command
    ///     types directly, mirroring the approach used by <see cref="Program" />.
    /// </summary>
    internal static class StubGenerator
    {
        private const string COMMANDS_NAMESPACE = "ClassicAssist.Data.Macros.Commands";

        public static void Generate( Assembly assembly, string outputPath )
        {
            // Command help text is localized; use en-US so descriptions/examples resolve.
            Thread.CurrentThread.CurrentCulture = CultureInfo.GetCultureInfo( "en-US" );
            Thread.CurrentThread.CurrentUICulture = CultureInfo.GetCultureInfo( "en-US" );

            Type cda = assembly.GetType( "ClassicAssist.Data.Macros.CommandsDisplayAttribute" );

            if ( cda == null )
            {
                Console.WriteLine( "Could not locate CommandsDisplayAttribute, skipping stub generation." );
                return;
            }

            List<Type> commandTypes = assembly.GetTypes()
                .Where( t => t.Namespace != null && t.IsPublic && t.IsClass &&
                             t.Namespace.EndsWith( "Macros.Commands" ) )
                .OrderBy( t => t.Name )
                .ToList();

            Console.WriteLine( $"Generating Python stubs for {commandTypes.Count} command modules..." );

            if ( Directory.Exists( outputPath ) )
            {
                Directory.Delete( outputPath, true );
            }

            // Namespaced tree, mirroring the imports the macro host injects at runtime
            // (from ClassicAssist.Data.Macros.Commands.XCommands import *).
            string namespacePath = Path.Combine( outputPath, "ClassicAssist", "Data", "Macros", "Commands" );
            Directory.CreateDirectory( namespacePath );

            List<string> flatBlocks = new List<string>();

            foreach ( Type type in commandTypes )
            {
                string moduleBody = GenerateModuleBody( type, cda );

                File.WriteAllText( Path.Combine( namespacePath, $"{type.Name}.pyi" ), Header() + moduleBody );

                flatBlocks.Add( $"# region {type.Name}\n\n{moduleBody}" );
            }

            GenerateNamespaceInitFiles( outputPath, commandTypes );

            // Flat globals shim: a single self-contained file with every command as a top-level
            // function, for users who want zero-import autocomplete via a configured stub path.
            string flatBody = Header() + string.Join( "\n", flatBlocks );
            File.WriteAllText( Path.Combine( outputPath, "ClassicAssistMacros.pyi" ), flatBody );

            Console.WriteLine( $"Python stubs generated to: {outputPath}" );
        }

        private static string Header()
        {
            StringBuilder sb = new StringBuilder();
            sb.AppendLine( "# -*- coding: utf-8 -*-" );
            sb.AppendLine( "\"\"\"Autogenerated Python stub file for macro commands. Do not edit manually.\"\"\"" );
            sb.AppendLine( "from typing import Any" );
            sb.AppendLine();
            return sb.ToString();
        }

        private static string GenerateModuleBody( Type type, Type cda )
        {
            StringBuilder sb = new StringBuilder();

            IEnumerable<MethodInfo> methods = type
                .GetMethods( BindingFlags.Public | BindingFlags.Static | BindingFlags.DeclaredOnly )
                .Where( m =>
                {
                    try
                    {
                        return m.GetCustomAttribute( cda ) != null;
                    }
                    catch
                    {
                        return false;
                    }
                } )
                .OrderBy( m => m.Name );

            foreach ( MethodInfo method in methods )
            {
                GenerateMethodStub( method, cda, sb );
            }

            return sb.ToString();
        }

        private static void GenerateMethodStub( MethodInfo method, Type cda, StringBuilder sb )
        {
            dynamic attr = null;

            try
            {
                attr = method.GetCustomAttribute( cda );
            }
            catch
            {
                // Ignore methods with a CommandsDisplay attribute that fails to construct.
            }

            List<string> paramStrs = new List<string>();

            foreach ( ParameterInfo param in method.GetParameters() )
            {
                if ( param.IsOut )
                {
                    continue;
                }

                string paramType = GetPythonTypeName( param.ParameterType );
                string defaultStr = GetDefaultValueString( param );

                paramStrs.Add( string.IsNullOrEmpty( defaultStr )
                    ? $"{param.Name}: {paramType}"
                    : $"{param.Name}: {paramType} = {defaultStr}" );
            }

            string returnType = GetPythonTypeName( method.ReturnType );

            if ( paramStrs.Count == 0 )
            {
                sb.AppendLine( $"def {method.Name}() -> {returnType}:" );
            }
            else if ( paramStrs.Count == 1 )
            {
                sb.AppendLine( $"def {method.Name}({paramStrs[0]}) -> {returnType}:" );
            }
            else
            {
                sb.AppendLine( $"def {method.Name}(" );

                for ( int i = 0; i < paramStrs.Count; i++ )
                {
                    sb.AppendLine( i < paramStrs.Count - 1 ? $"    {paramStrs[i]}," : $"    {paramStrs[i]}" );
                }

                sb.AppendLine( $") -> {returnType}:" );
            }

            string description = attr != null ? (string) attr.Description : null;
            string example = attr != null ? (string) attr.Example : null;

            sb.AppendLine( "    \"\"\"" );

            if ( !string.IsNullOrEmpty( description ) )
            {
                foreach ( string line in description.Split( '\n' ) )
                {
                    string trimmed = line.Trim();

                    if ( !string.IsNullOrEmpty( trimmed ) )
                    {
                        sb.AppendLine( $"    {trimmed}" );
                    }
                }
            }

            if ( !string.IsNullOrEmpty( example ) )
            {
                sb.AppendLine();
                sb.AppendLine( "    Example:" );

                foreach ( string line in example.Split( '\n' ) )
                {
                    sb.AppendLine( $"        {line.TrimEnd()}" );
                }
            }

            sb.AppendLine( "    \"\"\"" );
            sb.AppendLine( "    ..." );
            sb.AppendLine();
        }

        private static string GetPythonTypeName( Type type )
        {
            if ( type == typeof( void ) )
            {
                return "None";
            }

            if ( type == typeof( bool ) )
            {
                return "bool";
            }

            if ( type == typeof( string ) )
            {
                return "str";
            }

            if ( type == typeof( float ) || type == typeof( double ) || type == typeof( decimal ) )
            {
                return "float";
            }

            if ( type == typeof( int ) || type == typeof( uint ) || type == typeof( short ) ||
                 type == typeof( ushort ) || type == typeof( byte ) || type == typeof( sbyte ) ||
                 type == typeof( long ) || type == typeof( ulong ) || type.IsEnum )
            {
                return "int";
            }

            if ( type.IsArray || typeof( IEnumerable ).IsAssignableFrom( type ) && type != typeof( string ) )
            {
                return "list";
            }

            return "Any";
        }

        private static string GetDefaultValueString( ParameterInfo param )
        {
            if ( !param.HasDefaultValue )
            {
                return null;
            }

            object value = param.DefaultValue;

            if ( value == null )
            {
                return "None";
            }

            if ( value is bool b )
            {
                return b ? "True" : "False";
            }

            if ( value is string s )
            {
                return $"\"{s}\"";
            }

            if ( value is float || value is double )
            {
                return Convert.ToString( value, CultureInfo.InvariantCulture );
            }

            if ( value.GetType().IsPrimitive )
            {
                return Convert.ToString( value, CultureInfo.InvariantCulture );
            }

            if ( value.GetType().IsEnum )
            {
                return Convert.ToString( Convert.ToInt64( value ), CultureInfo.InvariantCulture );
            }

            return "...";
        }

        private static void GenerateNamespaceInitFiles( string outputPath, IEnumerable<Type> commandTypes )
        {
            StringBuilder commandsInit = new StringBuilder();
            commandsInit.AppendLine( "# -*- coding: utf-8 -*-" );
            commandsInit.AppendLine();

            foreach ( Type type in commandTypes )
            {
                commandsInit.AppendLine( $"from .{type.Name} import *" );
            }

            File.WriteAllText(
                Path.Combine( outputPath, "ClassicAssist", "Data", "Macros", "Commands", "__init__.pyi" ),
                commandsInit.ToString() );

            string[] parentInits =
            {
                Path.Combine( "ClassicAssist", "__init__.pyi" ),
                Path.Combine( "ClassicAssist", "Data", "__init__.pyi" ),
                Path.Combine( "ClassicAssist", "Data", "Macros", "__init__.pyi" )
            };

            foreach ( string parentInit in parentInits )
            {
                File.WriteAllText( Path.Combine( outputPath, parentInit ), "# -*- coding: utf-8 -*-\n" );
            }
        }
    }
}
